In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
from IPython.display import display
%matplotlib inline

In [10]:
# Display the number of columns

loan_df = pd.read_csv('train.csv')
display(loan_df)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [ ]:
# columns 

loan_df.columns

In [5]:
loan_df.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

In [4]:
loan_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [ ]:
loan_df.groupby('Loan_Status').ApplicantIncome.sum().plot(kind='bar')

In [ ]:
loan_df.groupby('Loan_Status').CoapplicantIncome.sum().plot(kind='bar')

In [ ]:
# delete rows with missing loan amount and loan term 

# indexToDrop = loan_df[ (loan_df['Loan_Status'] == "Y")  & (loan_df['LoanAmount'].isna() ) ].index

# loan_df.dropna(inplace=True, axis=0)

# loan_df.drop(indexToDrop, inplace=True)
# loan_df

In [28]:
# change the value of loan status to 1 or 0
loan_df.loc[loan_df['Loan_Status'] == 'Y','Loan_Status']=  1
loan_df.loc[loan_df['Loan_Status'] == 'N','Loan_Status']=  0

# fill nan with mean
#loan_df = loan_df.fillna(loan_df.mean())

#outcomes = loan_df['Loan_Status']

#features_raw = loan_df.drop('Loan_Status', axis=1)
display(features_raw.head())

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001002,Male,No,0,Graduate,No,5849,0.0,146.412162,360.0,1.0,Urban
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.000000,360.0,1.0,Rural
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.000000,360.0,1.0,Urban
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.000000,360.0,1.0,Urban
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.000000,360.0,1.0,Urban

In [31]:
# features_no_id = features_raw.drop(['Loan_ID'],axis=1)
# features_no_id

# one-hot-encoding
features = pd.get_dummies(features_no_id)

# #fill in the blanks
# features =  features.fillna(0.0)
# display(features.head())

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Gender_Female,Gender_Male,Married_No,Married_Yes,Dependents_0,Dependents_1,Dependents_2,Dependents_3+,Education_Graduate,Education_Not Graduate,Self_Employed_No,Self_Employed_Yes,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban
0,5849,0.0,146.412162,360.0,1.0,0,1,1,0,1,0,0,0,1,0,1,0,0,0,1
1,4583,1508.0,128.000000,360.0,1.0,0,1,0,1,0,1,0,0,1,0,1,0,1,0,0
2,3000,0.0,66.000000,360.0,1.0,0,1,0,1,1,0,0,0,1,0,0,1,0,0,1
3,2583,2358.0,120.000000,360.0,1.0,0,1,0,1,1,0,0,0,0,1,1,0,0,0,1
4,6000,0.0,141.000000,360.0,1.0,0,1,1,0,1,0,0,0,1,0,1,0,0,0,1

In [32]:
# train the data 
from sklearn.model_selection import train_test_split
X_train, x_test, Y_train, y_test = train_test_split(features, outcomes, test_size=0.2, random_state=42)

In [33]:
# import the classifier and fit the data 
from sklearn.tree import DecisionTreeClassifier


decision = DecisionTreeClassifier() 
decision.fit(X_train, Y_train)
loan_pred = decision.predict(X_train)
test_pred = decision.predict(x_test)

from sklearn.metrics import accuracy_score
train_accurracy = accuracy_score(Y_train,loan_pred)
print('The training accurracy is: ', train_accurracy)

# test_data = pd.read_csv('test.csv')
test_accuracy = accuracy_score(y_test, test_pred)
print('The test accurracy: ', test_accuracy)

DecisionTreeClassifier()

The training accurracy is:  1.0
The test accurracy:  0.6747967479674797

In [54]:
# Tweak The model 

decision = DecisionTreeClassifier(max_depth=6,min_samples_leaf=5, min_samples_split=10) 
decision.fit(X_train, Y_train)


loan_pred = decision.predict(X_train)
test_pred = decision.predict(x_test)

train_accurracy = accuracy_score(Y_train,loan_pred)
print('The training accurracy is: ', train_accurracy)

# test_data = pd.read_csv('test.csv')
test_accuracy = accuracy_score(y_test, test_pred)
print('The test accurracy: ', test_accuracy)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=5, min_samples_split=10)

In [59]:
from sklearn.ensemble import RandomForestClassifier

forest = RandomForestClassifier(criterion='entropy')
forest.fit(X_train, Y_train)

loan_pred = forest.predict(X_train)
test_pred = forest.predict(x_test)

train_accurracy = accuracy_score(Y_train,loan_pred)
print('The training accurracy is: ', train_accurracy)

# test_data = pd.read_csv('test.csv')
test_accuracy = accuracy_score(y_test, test_pred)
print('The test accurracy: ', test_accuracy)

RandomForestClassifier(criterion='entropy')

In [70]:
from sklearn.linear_model import LogisticRegression

logistic = LogisticRegression(max_iter=10000)
logistic.fit(X_train, Y_train)

loan_pred = logistic.predict(X_train)
test_pred = logistic.predict(x_test)

train_accurracy = accuracy_score(Y_train,loan_pred)
print('The training accurracy is: ', train_accurracy)

# test_data = pd.read_csv('test.csv')
test_accuracy = accuracy_score(y_test, test_pred)
print('The test accurracy: ', test_accuracy)

The training accurracy is:  0.8187372708757638
The test accurracy:  0.7642276422764228

In [68]:
from sklearn.ensemble import GradientBoostingClassifier

boost = GradientBoostingClassifier()
boost.fit(X_train, Y_train)

loan_pred = boost.predict(X_train)
test_pred = boost.predict(x_test)

train_accurracy = accuracy_score(Y_train,loan_pred)
print('The training accurracy is: ', train_accurracy)

# test_data = pd.read_csv('test.csv')
test_accuracy = accuracy_score(y_test, test_pred)
print('The test accurracy: ', test_accuracy)

The training accurracy is:  0.9022403258655805
The test accurracy:  0.7642276422764228